apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: searchengine
spec:
  containers:
  - name: postgres-client
    image: postgres:15
    command: ["sleep", "3600"]
    env:
    - name: PGPASSWORD
      value: "DBkonger1234"
  restartPolicy: Never