-- This file has been moved to scripts/init-schema.sql
-- 
-- The database schema is now managed separately from the Kubernetes manifest.
-- To initialize the database schema, use:
--
-- For local PostgreSQL:
--   psql -U username -d database -f scripts/init-schema.sql
--
-- For Kubernetes PostgreSQL:
--   kubectl cp scripts/init-schema.sql <pod-name>:/tmp/
--   kubectl exec -it <pod-name> -- psql -U ameliavalentin -d search -f /tmp/init-schema.sql
--
-- To import real data from SQLite:
--   scripts/export-data.sh