apiVersion: batch/v1
kind: Job
metadata:
  name: data-migration
  namespace: searchengine
spec:
  template:
    metadata:
      labels:
        app: data-migration
    spec:
      restartPolicy: Never
      containers:
      - name: migration
        image: datamigration:latest
        imagePullPolicy: Never
        args: ["Server=postgres;Port=5432;User Id=ameliavalentin;Password=DBkonger1234;Database=search;"]
        env:
        - name: DOTNET_ENVIRONMENT
          value: "Production"
      # Wait for databases to be ready
      initContainers:
      - name: wait-for-postgres
        image: postgres:15
        env:
        - name: PGPASSWORD
          value: "DBkonger1234"
        command: ['sh', '-c', 'until pg_isready -h postgres -p 5432 -U ameliavalentin; do echo waiting for source postgres; sleep 2; done;']
      - name: wait-for-postgres-words
        image: postgres:15
        env:
        - name: PGPASSWORD
          value: "DBkonger1234"
        command: ['sh', '-c', 'until pg_isready -h postgres-words -p 5432 -U ameliavalentin; do echo waiting for postgres-words; sleep 2; done;']
      - name: wait-for-postgres-documents
        image: postgres:15
        env:
        - name: PGPASSWORD
          value: "DBkonger1234"
        command: ['sh', '-c', 'until pg_isready -h postgres-documents -p 5432 -U ameliavalentin; do echo waiting for postgres-documents; sleep 2; done;']
      - name: wait-for-postgres-occurrences
        image: postgres:15
        env:
        - name: PGPASSWORD
          value: "DBkonger1234"
        command: ['sh', '-c', 'until pg_isready -h postgres-occurrences -p 5432 -U ameliavalentin; do echo waiting for postgres-occurrences; sleep 2; done;']